### PR TITLE
Big refactoring to simplify code and to allow in the future to push updates instead of poll

### PR DESCRIPTION
**Pull request by tronikos**
Big refactoring to simplify code and to allow in the future to push updates instead of poll. Now all the values of the sensors are kept in maps so it will be easier to detect changes. It will also be much easier to add any new sensors since you will only have to add a bit of Python code.

### CODE REVIEW

**Comment by Daniel-dev22** [comment]
Wow! Thank you for the pull request it will take some time to test this with both my water heater and HVAC and review it but so far it looks great especially the pre commit tests.

> Removed unused and likely not quite working yet cc_blower_cfm and cc_blower_rpm sensors

I didn't review everything just yet but I wanted to note cc_blower_cfm is working for Heatpumps and cc_blower_rpm is not 100% accurate yet with Heatpumps. I would leave them in.

Also I may merge my draft pr first so you can pull those changes (there's not a lot) but there would be some conflicts otherwise due to everything this pr touched.

**Comment by tronikos** [comment]
I'd appreciate it if you don't merge your #17 since it will make rebasing much harder. It will be trivial to apply your change after this. 
Your change will be limited to `components/econet/text_sensor/__init__.py` where you will need to add:
```
TEXT_SENSORS = {
    CONF_WATER_HEATER_FAN_SPEED: "FAN_CTRL",
}
```

I wasn't sure cc_blower_cfm and cc_blower_rpm were working because of all your attempts to read different bits from the binary response. I will have to think how we can take a similar generic approach to handle binary data.

**Comment by Daniel-dev22** [comment]
> I'd appreciate it if you don't merge your #17 since it will make rebasing much harder. It will be trivial to apply your change after this.

 alright well I will hold off then.

> I wasn't sure cc_blower_cfm and cc_blower_rpm were working because of all your attempts to read different bits from the binary response. I will have to think how we can take a similar generic approach to handle binary data.

Yes they work and there is another open pr that has a lot more support for furnaces of binary data but the op hasn't responded in awhile so I didn't merge it. It is very difficult to work with which is why I tried 3737 times as you saw lol.

**Comment by Daniel-dev22** [comment]
Superceded by #20

**Pull request closed without merging**
